### ISSUE TITLE
Compatibility with AngularAMD

### ISSUE THREAD

**Issue by MrMaxon** [davej/angular-classy#24]
Has anyone ever managed to get Classy to work with AngularAMD?

When I am trying to create a Classy controller, which gets loaded by AngularAMD I get the following error:

`Error: [ng:areq] Argument 'HomeCtrl' is not a function, got undefined`

**Comment by davej** [comment]
Closing as I'm not going to be working on this for 1.0, see #38.
